name: Deploy Vite App with Bun

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Link deps
        working-directory: ./packages/pill-watermark
        run: bun link

      - name: Install dependencies
        working-directory: ./apps/demo
        run: bun install

      - name: Build package
        working-directory: ./packages/pill-watermark
        run: bun run build

      - name: Build project
        working-directory: ./apps/demo
        run: bun run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./apps/demo/dist
